/* tslint:disable */
/* eslint-disable */
/**
 * User Task Manager API
 * A simple API to manage users and tasks.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dimakatsomm@icloud.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateUserDto
 */
export interface CreateUserDto {

    /**
     * @type {string}
     * @memberof CreateUserDto
     */
    username: string;

    /**
     * @type {string}
     * @memberof CreateUserDto
     */
    firstName: string;

    /**
     * @type {string}
     * @memberof CreateUserDto
     */
    lastName: string;
}
