services:
  user_task_mgr_db:
    container_name: user-task-mgr-db
    image: mongo:6
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  user_task_mgr_cache:
    container_name: user-task-mgr-cache
    image: redis:7
    restart: always
    env_file:
      - ./.env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ['redis-server', '--requirepass', REDIS_PASSWORD]
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis-data:/data

  user_task_mgr_api:
    container_name: user-task-mgr-api
    build:
      context: .
    restart: always
    env_file:
      - ./.env
    environment:
      - MONGOURI=${MONGOURI}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - 5000:5000
    depends_on:
      - user_task_mgr_db
      - user_task_mgr_cache
    volumes:
      - .:/app
  
volumes:
  mongo-data:
  redis-data:
